apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-ds
  namespace: kube-system
  labels:
    k8s-app: fluentd-ds
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: fluentd-ds
  template:
    metadata:
      labels:
        k8s-app: fluentd-ds
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
    spec:
      containers:
      - name: fluentd-ds
        image: 460570964411.dkr.ecr.us-east-1.amazonaws.com/charter/cse-k8s-logging-sidecar:v1.0.0-3fa58ef
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q -p /etc/fluent/plugins
        - name:  FLUENT_SPLUNK_HOST
          value: "http-inputs-charter.splunkcloud.com"
        - name:  FLUENT_SPLUNK_TOKEN
          value: "4970ABBC-9352-5FEA-90CB-FB3902D26BBF"
        - name: SPLUNK_INDEX
          value: "k8ngprd"
        - name: CLUSTER_NAME
          value: "specb-k8s.engprod-charter.net"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 15
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume
        configMap:
          name: fluentd-ds-config
