apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-ds
  namespace: kube-system
  labels:
    k8s-app: fluentd-ds
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-ds
  labels:
    k8s-app: fluentd-ds
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-ds
  labels:
    k8s-app: fluentd-ds
subjects:
- kind: ServiceAccount
  name: fluentd-ds
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-ds
  apiGroup: ""
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-ds
  namespace: kube-system
  labels:
    k8s-app: fluentd-ds
  annotations:
    roll: "__ROLL__"
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: fluentd-ds
  template:
    metadata:
      labels:
        k8s-app: fluentd-ds
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluentd-ds
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-ds
        image: __DOCKER_IMAGE__
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q -p /etc/fluent/plugins
        - name:  FLUENT_SPLUNK_HOST
          value: __FLUENT_SPLUNK_HOST__
        - name:  FLUENT_SPLUNK_TOKEN
          value: __FLUENT_SPLUNK_TOKEN__
        - name: SPLUNK_INDEX
          value: __SPLUNK_INDEX__
        - name: CLUSTER_NAME
          value: __CLUSTER_NAME__
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 15
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume
        configMap:
          name: fluentd-ds-config
